import {
  antFormType,
  antFormItemType,
  antInputType,
  antSingleInputComponentType,
  antMultiInputComponentType,
  antSearchInputComponentType,
  antPasswordInputComponentType,
  antAutoCompleteComponentType,
  antNumberInputComponentType,
  antMentionsInputComponentType,
  antTextComponentType,
  antSelectComponentType,
  antCascaderComponentType,
  antTreeSelectComponentType,
  antRadioGroupComponentType,
  antCheckboxComponentType,
  antSwitchComponentType,
  antSliderComponentType,
  antDatePickerComponentType,
  antRangePickerComponentType,
  antTimePickerComponentType,
  antMonthPickerComponentType,
  antWeekPickerComponentType,
  antDateComponentType,
  antRateComponentType,
  antUploadComponentType,
  RowComponentType,
} from '@/types/config';

const antForm: antFormType = {
  name: 'antForm',
  model: 'antModel',
  rules: 'antRules',
  ref: 'formRef',
  disabled: false,
  hideRequiredMark: false,
  labelAlign: 'right',
  layout: 'horizontal',
  labelCol: {
    span: 5,
    offset: 0,
  },
  wrapperCol: {
    span: 19,
    offset: 0,
  },
  gutter: [0, 0],
  colon: true,
  validateOnRuleChange: true,
  scrollToFirstError: false,
  validateTrigger: 'change',
};

const antFormItem: antFormItemType = {
  layout: 'col',
  label: '',
  size: 'default',
  rules: [],
  extra: '',
  help: '',
  htmlFor: '',
  labelCol: {
    span: 5,
    offset: 0,
  },
  wrapperCol: {
    span: 19,
    offset: 0,
  },
  name: '',
  autoLink: false,
  colon: antForm.colon,
  hasFeedback: false,
  labelAlign: 'right',
  required: false,
  validateFirst: false,
  validateTrigger: 'change',
  validateStatus: '',
};

const antInput: antInputType = {
  addonAfter: '',
  addonBefore: '',
  defaultValue: '',
  id: '',
  disabled: false,
  maxlength: 99,
  prefix: '',
  suffix: '',
  allowClear: true,
  placeholder: '',
};

const antDate: antDateComponentType = {
  allowClear: true,
  autofocus: false,
  disabled: false,
  mode: 'date',
  open: false,
  placeholder: '',
  dropdownClassName: '',
  inputReadOnly: false,
  valueFormat: '',
};

const antInputComponentList: Array<antSingleInputComponentType | antMultiInputComponentType|
antSearchInputComponentType | antPasswordInputComponentType | antAutoCompleteComponentType|
antNumberInputComponentType | antMentionsInputComponentType | antTextComponentType> = [
  {
    form: {
      ...antFormItem,
      label: '单行输入',
      name: 'single',
    },
    icon: 'single',
    title: '单行输入',
    tag: 'a-input',
    slots: [],
    config: {
      ...antInput,
      type: 'text',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '多行输入',
      name: 'multi',
    },
    icon: 'multi',
    title: '多行输入',
    tag: 'a-textarea',
    slots: [],
    config: {
      defaultValue: '',
      showCount: false,
      allowClear: false,
      autosize: false,
      maxlength: 99,
      disabled: false,
      placeholder: '',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '搜索输入',
      name: 'search',
    },
    icon: 'search',
    title: '搜索输入',
    tag: 'a-input-search',
    slots: [],
    config: {
      ...antInput,
      enterButton: false,
      loading: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '密码输入',
      name: 'password',
    },
    icon: 'password',
    title: '密码输入',
    tag: 'a-input-password',
    slots: [],
    config: {
      ...antInput,
      visibilityToggle: true,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '建议输入',
      name: 'auto',
    },
    icon: 'auto',
    title: '建议输入',
    tag: 'a-auto-complete',
    slots: [],
    config: {
      allowClear: false,
      autofocus: false,
      backfill: false,
      '#default': '',
      defaultActiveFirstOption: true,
      disabled: false,
      filterOption: false,
      optionLabelProp: 'children',
      placeholder: '',
      defaultOpen: false,
      open: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '数字输入',
      name: 'number',
    },
    icon: 'number',
    title: '数字输入',
    tag: 'a-input-number',
    slots: [],
    config: {
      autofocus: false,
      defaultValue: 0,
      disabled: false,
      max: Infinity,
      min: -Infinity,
      precision: 0,
      decimalSeparator: '',
      step: 1,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '触发输入',
      name: 'mentions',
    },
    icon: 'mentions',
    title: '触发输入',
    tag: 'a-mentions',
    slots: [],
    config: {
      autofocus: false,
      defaultValue: '',
      filterOption: false,
      placement: 'bottom',
      prefix: ['@'],
      split: ' ',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '富文编辑',
      name: 'text',
    },
    icon: 'text',
    title: '富文编辑',
    tag: 'a-text',
    slots: [],
    config: {},
  },
];

const selectComponentList: Array<antSelectComponentType | antCascaderComponentType |
antTreeSelectComponentType | antRadioGroupComponentType | antCheckboxComponentType |
antSwitchComponentType | antSliderComponentType | antDatePickerComponentType |
antTimePickerComponentType | antMonthPickerComponentType | antWeekPickerComponentType |
antRangePickerComponentType | antRateComponentType | antUploadComponentType> = [
  {
    form: {
      ...antFormItem,
      label: '下拉选择',
      name: 'select',
    },
    icon: 'select',
    title: '下拉选择',
    tag: 'a-select',
    slots: [],
    config: {
      allowClear: false,
      autoClearSearchValue: true,
      autofocus: false,
      bordered: true,
      defaultActiveFirstOption: true,
      disabled: false,
      dropdownClassName: '',
      dropdownMatchSelectWidth: true,
      filterOption: true,
      firstActiveValue: [],
      labelInValue: false,
      maxTagCount: 9,
      maxTagTextLength: 9,
      mode: null,
      notFoundContent: '',
      optionFilterProp: 'value',
      optionLabelProp: 'children',
      placeholder: '',
      showSearch: false,
      showArrow: true,
      tokenSeparators: [],
      defaultOpen: false,
      open: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '级联选择',
      name: 'cascader',
    },
    icon: 'cascader',
    title: '级联选择',
    tag: 'a-cascader',
    slots: [],
    config: {
      allowClear: true,
      autofocus: false,
      changeOnSelect: false,
      defaultValue: [],
      disabled: false,
      expandTrigger: 'click',
      notFoundContent: '',
      placeholder: '',
      popupClassName: '',
      popupPlacement: 'bottomLeft',
      popupVisible: false,
      showSearch: false,
      suffixIcon: '',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '树型选择',
      name: 'tree',
    },
    icon: 'tree',
    title: '树型选择',
    tag: 'a-tree-select',
    slots: [],
    config: {
      allowClear: false,
      defaultValue: [],
      disabled: false,
      dropdownClassName: '',
      dropdownMatchSelectWidth: true,
      labelInValue: false,
      maxTagCount: 9,
      multiple: false,
      placeholder: '',
      searchPlaceholder: '',
      searchValue: '',
      treeIcon: false,
      showCheckedStrategy: 'SHOW_CHILD',
      showSearch: false,
      suffixIcon: '',
      treeCheckable: false,
      treeCheckStrictly: false,
      treeDataSimpleMode: false,
      treeDefaultExpandAll: false,
      treeNodeFilterProp: 'value',
      treeNodeLabelProp: 'title',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '单选框组',
      name: 'radio',
    },
    icon: 'radio',
    title: '单选框组',
    tag: 'a-radio',
    slots: [],
    config: {
      defaultValue: '',
      disabled: false,
      name: '',
      buttonStyle: 'outline',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '复选框组',
      name: 'checkbox',
    },
    icon: 'checkbox',
    title: '复选框组',
    tag: 'a-checkbox-group',
    slots: [],
    config: {
      disabled: false,
      name: '',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '滑动开关',
      name: 'switch',
    },
    icon: 'switch',
    title: '滑动开关',
    tag: 'a-switch',
    slots: [],
    config: {
      autofocus: false,
      checked: false,
      disabled: false,
      loading: false,
      checkedChildren: '',
      unCheckedChildren: '',
      checkedValue: true,
      unCheckedValue: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '滑动输入',
      name: 'slider',
    },
    icon: 'slider',
    title: '滑动输入',
    tag: 'a-slider',
    slots: [],
    config: {
      autofocus: false,
      disabled: false,
      dots: false,
      included: false,
      max: 100,
      min: 0,
      range: false,
      reverse: false,
      step: 1,
      vertical: false,
      tooltipPlacement: '',
      tooltipVisible: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '日期选择',
      name: 'date',
    },
    icon: 'date',
    title: '日期选择',
    tag: 'a-date-picker',
    slots: [],
    config: {
      ...antDate,
      defaultPickerValue: '',
      format: '',
      showTime: false,
      showToday: true,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '时间选择',
      name: 'time',
    },
    icon: 'time',
    title: '时间选择',
    tag: 'a-time-picker',
    slots: [],
    config: {
      allowClear: true,
      autofocus: false,
      clearText: 'clear',
      defaultValue: '',
      disabled: false,
      format: '',
      hideDisabledOptions: false,
      hourStep: 1,
      inputReadOnly: false,
      minuteStep: 1,
      open: false,
      placeholder: '请选择时间',
      popupClassName: '',
      secondStep: 1,
      suffixIcon: '',
      clearIcon: '',
      use12Hours: false,
      valueFormat: '',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '月份选择',
      name: 'month',
    },
    icon: 'month',
    title: '月份选择',
    tag: 'a-month-picker',
    slots: [],
    config: {
      ...antDate,
      defaultPickerValue: '',
      format: 'YYYYY-MM',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '咒术选择',
      name: 'week',
    },
    icon: 'week',
    title: '周数选择',
    tag: 'a-week-picker',
    slots: [],
    config: {
      ...antDate,
      defaultPickerValue: '',
      format: '',
    },
  },
  {
    form: {
      ...antFormItem,
      label: '日期范围',
      name: 'DateScope',
    },
    icon: 'DateScope',
    title: '日期范围',
    tag: 'a-range-picker',
    slots: [],
    config: {
      ...antDate,
      defaultPickerValue: '',
      format: '',
      separator: '',
      showTime: false,
    },
  },
  // {
  //   icon: 'TimeScope',
  //   title: '时间范围',
  // },
  {
    form: {
      ...antFormItem,
      label: '评分',
      name: 'rate',
    },
    icon: 'rate',
    title: '评分',
    tag: 'a-rate',
    slots: [],
    config: {
      allowClear: true,
      allowHalf: false,
      autofocus: false,
      character: '',
      count: 5,
      disabled: false,
    },
  },
  {
    form: {
      ...antFormItem,
      label: '上传',
      name: 'upload',
    },
    icon: 'upload',
    title: '上传',
    tag: 'a-upload',
    slots: [],
    config: {
      accept: '',
      action: '',
      method: 'post',
      directory: false,
      disabled: false,
      listType: 'text',
      multiple: false,
      name: 'file',
      showUploadList: true,
      supportServerRender: false,
      withCredentials: false,
      openFileDialogOnClick: true,
    },
  },
];

const layoutComponentList: Array<RowComponentType> = [];

const componentList: Array<{
  title: string,
  icon: string,
  componentList: Array<antSingleInputComponentType | antMultiInputComponentType |
  antSearchInputComponentType | antPasswordInputComponentType | antAutoCompleteComponentType |
  antNumberInputComponentType | antMentionsInputComponentType | antTextComponentType |
  antSelectComponentType | antTreeSelectComponentType |
  antRadioGroupComponentType | antCheckboxComponentType | antSwitchComponentType |
  antSliderComponentType | antDatePickerComponentType | antRangePickerComponentType |
  antTimePickerComponentType | antMonthPickerComponentType | antWeekPickerComponentType |
  antRateComponentType | antUploadComponentType | RowComponentType>
}> = [
  {
    icon: 'input',
    title: '输入型组件',
    componentList: antInputComponentList,
  },
  {
    icon: 'choose',
    title: '选择型组件',
    componentList: selectComponentList,
  },
  {
    icon: 'component',
    title: '布局型组件',
    componentList: layoutComponentList,
  },
];

export {
  antForm,
  componentList,
  antInputComponentList,
  selectComponentList,
  layoutComponentList,
};
